# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sapphire < Formula
  desc "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal."
  homepage "https://github.com/duggal1/Sapphire-cli"
  version "0.1.4"
  license "FSL-1.1-MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/duggal1/Sapphire-cli/releases/download/v0.1.4/sapphire_0.1.4_Darwin_x86_64.tar.gz"
    sha256 "19055c7a34d7397c5efcf35081de3dccbfe7912f8c9bb0689547aab04656f37e"

    define_method(:install) do
      bin.install "sapphire"
      bash_completion.install "completions/sapphire.bash" => "sapphire"
      zsh_completion.install "completions/sapphire.zsh" => "_sapphire"
      fish_completion.install "completions/sapphire.fish"
      man1.install "manpages/sapphire.1.gz"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/duggal1/Sapphire-cli/releases/download/v0.1.4/sapphire_0.1.4_Darwin_arm64.tar.gz"
    sha256 "1aad1619c9255ce7e1e7dad18acb9e3ee331f741c9d88a9aa3415a6b6ed1ba7f"

    define_method(:install) do
      bin.install "sapphire"
      bash_completion.install "completions/sapphire.bash" => "sapphire"
      zsh_completion.install "completions/sapphire.zsh" => "_sapphire"
      fish_completion.install "completions/sapphire.fish"
      man1.install "manpages/sapphire.1.gz"
    end
  end
end
