# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sapphire < Formula
  desc "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal."
  homepage "https://github.com/duggal1/Sapphire-cli"
  version "0.1.6"
  license "FSL-1.1-MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/duggal1/Sapphire-cli/releases/download/v0.1.6/sapphire_0.1.6_Darwin_x86_64.tar.gz"
    sha256 "717fd48406fbcd186cf86915aa030725638611c5134afbad87ddb7c16fe4b18e"

    define_method(:install) do
      bin.install "sapphire"
      bash_completion.install "completions/sapphire.bash" => "sapphire"
      zsh_completion.install "completions/sapphire.zsh" => "_sapphire"
      fish_completion.install "completions/sapphire.fish"
      man1.install "manpages/sapphire.1.gz"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/duggal1/Sapphire-cli/releases/download/v0.1.6/sapphire_0.1.6_Darwin_arm64.tar.gz"
    sha256 "c861449caabfb3f95330cf15f23135712c034527c0e12b75b811668ec436198b"

    define_method(:install) do
      bin.install "sapphire"
      bash_completion.install "completions/sapphire.bash" => "sapphire"
      zsh_completion.install "completions/sapphire.zsh" => "_sapphire"
      fish_completion.install "completions/sapphire.fish"
      man1.install "manpages/sapphire.1.gz"
    end
  end
end
