# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sapphire < Formula
  desc "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal."
  homepage "https://github.com/duggal1/Sapphire-cli"
  version "0.1.5"
  license "FSL-1.1-MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/duggal1/Sapphire-cli/releases/download/v0.1.5/sapphire_0.1.5_Darwin_x86_64.tar.gz"
    sha256 "3af4d436059afcc1c405b922d21237f03fa72b296b6e5ed2fe90b746ed181945"

    define_method(:install) do
      bin.install "sapphire"
      bash_completion.install "completions/sapphire.bash" => "sapphire"
      zsh_completion.install "completions/sapphire.zsh" => "_sapphire"
      fish_completion.install "completions/sapphire.fish"
      man1.install "manpages/sapphire.1.gz"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/duggal1/Sapphire-cli/releases/download/v0.1.5/sapphire_0.1.5_Darwin_arm64.tar.gz"
    sha256 "6b08972d16829f9cb3c466d7a19e026e6b76f2284b6126c7616024c224b0076b"

    define_method(:install) do
      bin.install "sapphire"
      bash_completion.install "completions/sapphire.bash" => "sapphire"
      zsh_completion.install "completions/sapphire.zsh" => "_sapphire"
      fish_completion.install "completions/sapphire.fish"
      man1.install "manpages/sapphire.1.gz"
    end
  end
end
